Hash passwords en registro, cambio de contraseña y login.
airaup/airaup-sgi pull request #4
Opened 2018-10-25 04:19 UTC by david-rivero

Issue a resolver: https://github.com/airaup/airaup-sgi/issues/3

2018-10-26 17:07 UTC, fuxes commented
Parece que está excelente.
Lo único es que habría que mandar el PR contra la rama `develop`, no contra la rama `master`.

También, podrías agregar un script en /hack para actualizar la bd?
Si mergeamos esto así como está los usuarios no van a poder loguearse porq actualmente no tienen la passwd encriptada.

2018-10-26 17:07 UTC, fuxes commented
Parece que está excelente.
Lo único es que habría que mandar el PR contra la rama develop, no contra la rama master.

También, podrías agregar un script en /hack para actualizar la bd?
Si mergeamos esto así como está los usuarios no van a poder loguearse porq actualmente no tienen la passwd encriptada.

2018-10-26 17:12 UTC, fuxes commented
Ahí hice el cambio del para que se haga el merge contra `develop`.

Faltaría el script, correrlo y actualizar el dump. Cualquier cosa avisame y te doy una mano con eso.

2018-10-27 12:28 UTC, fuxes requested changes
Faltaría un script que actualice la bd con passwords hasheados, correrlo y actualizar el dump. Si mergeamos así como está nos va a romper a todos el environment.

2018-10-27 12:28 UTC, fuxes commented on sgi/src/cambiarpwd.php
>          if ($socio['Password'] == $pwdActual) { //SI COINCIDEN, SE CAMBIA EL PWD
Fijate que acá va a checkear el password. Debería desencriptar, checkear si es el mismo password, y recién ahí volver a encriptar.

2018-10-27 12:28 UTC, fuxes commented on sgi/src/login.php
> +    $checkPassword=password_verify($pwd, $socio["Password"]);
Esta variable tiene más nombre de función que de boolean. Quizás algo como `$passwordIsCorrect` o algo así.

2018-11-02 04:33 UTC, david-rivero commented
Al final agregue un script en php que se ejecuta cuando se levanta la instancia de web en docker, antes de correr el server. La idea es usarlo una vez, y luego desecharlo.

2018-11-02 11:22 UTC, david-rivero commented
Los ultimos commits fueron por un conflicto en el merge, y me quedaron desprolijos a nivel de cambios en los files y el historial, no se si es preferible cerrar este PR y subir uno nuevo y mas prolijo, o seguimos adelante y de ultima hacemos squash en los commits.

2018-11-07 01:52 UTC, closed without merging

2018-11-07 02:03 UTC, david-rivero commented
Este PR quedo deprecado, el nuevo PR es este:
https://github.com/airaup/airaup-sgi/pull/15